spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,public/**,templates/**,META-INF/**
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: validate   # 초기 개발 단계엔 update로 바꿔도 되나, 습관 들이려면 validate + 별도 마이그레이션 툴(Flyway 등) 권장
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
      jakarta.persistence.database-product-name: PostgreSQL
      jakarta.persistence.database-product-version: 16.0
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        format_sql: false
        use_sql_comments: false
        check_nullability: false
    open-in-view: false     # OSIV 끄기 - 트랜잭션 경계를 명시적으로 관리하는 습관을 들이기 위함
decorator:
  datasource:
    p6spy:
      multiline: false
      logging: slf4j
      log-filter:
        pattern: "^(?!.*(?i)(TB_CONECT_HIST_INFO|tb_blclst_user|session_id)).*$"
logging:
  level:
    org.hibernate.SQL: debug
